Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Controllers/Weixin/Open/OpenOAuthController.cs
//DPBMARK_FILE Open
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Senparc.Weixin.Exceptions;
using Senparc.CO2NET.Extensions;
using Senparc.Weixin.MP.Sample.CommonService.OpenTicket;
using Senparc.Weixin.Open.CommonAPIs;
using Senparc.Weixin.Open.ComponentAPIs;
using Senparc.Weixin.Open.Containers;

namespace Senparc.Weixin.Sample.NetCore3.Controllers
{

    public class OpenOAuthController : BaseController
    {
        private string component_AppId = Config.SenparcWeixinSetting.Component_Appid;
        private string component_Secret = Config.SenparcWeixinSetting.Component_Secret;
        //private static string ComponentAccessToken = null;//需要授权获取，腾讯服务器会主动推送

        #region 开放平台入口及回调

        /// <summary>
        /// OAuthScope.snsapi_userinfo方式回调
        /// </summary>
        /// <param name="auth_code"></param>
        /// <param name="expires_in"></param>
        /// <param name="appId"></param>
        /// <returns></returns>
        public ActionResult OpenOAuthCallback(string auth_code, int expires_in, string appId)
        {
            try
            {

                #region 直接调用API

                //string openTicket = OpenTicketHelper.GetOpenTicket(component_AppId);
                //var component_access_token = Open.ComponentAPIs.ComponentApi.GetComponentAccessToken(component_AppId, component_Secret, openTicket).component_access_token;
                //ComponentAccessToken = component_access_token;
                //var oauthResult = Open.ComponentAPIs.ComponentApi.QueryAuth(component_access_token, component_AppId, auth_code);

                ////TODO:储存oauthResult.authorization_info
                //var authInfoResult = Open.ComponentAPIs.ComponentApi.GetAuthorizerInfo(component_access_token, component_AppId,
                //     oauthResult.authorization_info.authorizer_appid);

                #endregion

                #region 使用ComponentContainer

                //获取OAuth授权结果
                QueryAuthResult queryAuthResult;
                try
                {
                    queryAuthResult = ComponentContainer.GetQueryAuthResult(component_AppId, auth_code);
                }
                catch (Exception ex)
                {
                    throw new Exception("QueryAuthResult：" + ex.Message);
                }
                #endregion

                var authorizerInfoResult = AuthorizerContainer.GetAuthorizerInfoResult(component_AppId,
                    queryAuthResult.authorization_info.authorizer_appid);

                ViewData["QueryAuthorizationInfo"] = queryAuthResult.authorization_info;
                ViewData["GetAuthorizerInfoResult"] = authorizerInfoResult.authorizer_info;

                return View();
            }
            catch (ErrorJsonResultException ex)
            {
                return Content(ex.Message);
            }
        }


        /// <summary>
        /// 公众号授权页入口
        /// </summary>
        /// <returns></returns>
        public ActionResult JumpToMpOAuth()
        {
            return View();
        }

        #endregion

        #region 微信用户授权相关

        public ActionResult Index(string appId)
        {
            //此页面引导用户点击授权
            ViewData["UrlUserInfo"] = Open.OAuthAPIs.OAuthApi.GetAuthorizeUrl(appId, component_AppId, "http://sdk.weixin.senparc.com/OpenOAuth/UserInfoCallback", "JeffreySu", new[] { Open.OAuthScope.snsapi_userinfo, Open.OAuthScope.snsapi_base });
            ViewData["UrlBase"] = Open.OAuthAPIs.OAuthApi.GetAuthorizeUrl(appId, component_AppId, "http://sdk.weixin.senparc.com/OpenOAuth/BaseCallback", "JeffreySu", new[] { Open.OAuthScope.snsapi_userinfo, Open.OAuthScope.snsapi_base });
            return View();
        }

        /// <summary>
        /// OAuthScope.snsapi_userinfo方式回调
        /// </summary>
        /// <param name="code"></param>
        /// <param name="state"></param>
        /// <param name="appId"></param>
        /// <returns></returns>
        public ActionResult UserInfoCallback(string code, string state, string appId)
        {
            if (string.IsNullOrEmpty(code))
            {
                return Content("您拒绝了授权！");
            }

            if (state != "JeffreySu")
            {
                //这里的state其实是会暴露给客户端的，验证能力很弱，这里只是演示一下
                //实际上可以存任何想传递的数据，比如用户ID，并且需要结合例如下面的Session["OAuthAccessToken"]进行验证
                return Content("验证失败！请从正规途径进入！");
            }

            Open.OAuthAPIs.OAuthAccessTokenResult result = null;

            //通过，用code换取access_token
            try
            {
                var componentAccessToken = ComponentContainer.GetComponentAccessToken(component_AppId);
                result = Open.OAuthAPIs.OAuthApi.GetAccessToken(appId, component_AppId, componentAccessToken, code);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

            if (result.errcode != ReturnCode.请求成功)
            {
                return Content("错误：" + result.errmsg);
            }
            //下面2个数据也可以自己封装成一个类，储存在数据库中（建议结合缓存）
            //如果可以确保安全，可以将access_token存入用户的cookie中，每一个人的access_token是不一样的
            HttpContext.Session.SetString("OAuthAccessTokenStartTime", SystemTime.Now.ToString());
            HttpContext.Session.SetString("OAuthAccessToken", result.ToJson());

            //因为第一步选择的是OAuthScope.snsapi_userinfo，这里可以进一步获取用户详细信息
            try
            {
                Open.OAuthAPIs.OAuthUserInfo userInfo = Open.OAuthAPIs.OAuthApi.GetUserInfo(result.access_token, result.openid);
                return View(userInfo);
            }
            catch (ErrorJsonResultException ex)
            {
                return Content(ex.Message);
            }
        }

        /// <summary>
        /// OAuthScope.snsapi_base方式回调
        /// </summary>
        /// <param name="code"></param>
        /// <param name="state"></param>
        /// <returns></returns>
        public ActionResult BaseCallback(string code, string state, string appId)
        {
            if (string.IsNullOrEmpty(code))
            {
                return Content("您拒绝了授权！");
            }

            if (state != "JeffreySu")
            {
                //这里的state其实是会暴露给客户端的，验证能力很弱，这里只是演示一下
                //实际上可以存任何想传递的数据，比如用户ID，并且需要结合例如下面的Session["OAuthAccessToken"]进行验证
                return Content("验证失败！请从正规途径进入！");
            }

            //通过，用code换取access_token
            var componentAccessToken = ComponentContainer.TryGetComponentAccessToken(component_AppId, component_Secret);

            var result = Open.OAuthAPIs.OAuthApi.GetAccessToken(appId, component_AppId, componentAccessToken, code);//TODO:使用Container

            if (result.errcode != ReturnCode.请求成功)
            {
                return Content("错误：" + result.errmsg);
            }

            //下面2个数据也可以自己封装成一个类，储存在数据库中（建议结合缓存）
            //如果可以确保安全，可以将access_token存入用户的cookie中，每一个人的access_token是不一样的
            HttpContext.Session.SetString("OAuthAccessTokenStartTime", SystemTime.Now.ToString());
            HttpContext.Session.SetString("OAuthAccessToken", result.ToJson());


            //因为这里还不确定用户是否关注本微信，所以只能试探性地获取一下
            Open.OAuthAPIs.OAuthUserInfo userInfo = null;
            try
            {
                //已关注，可以得到详细信息
                userInfo = Open.OAuthAPIs.OAuthApi.GetUserInfo(result.access_token, result.openid);
                ViewData["ByBase"] = true;
                return View("UserInfoCallback", userInfo);
            }
            catch (ErrorJsonResultException ex)
            {
                //未关注，只能授权，无法得到详细信息
                //这里的 ex.JsonResult 可能为："{\"errcode\":40003,\"errmsg\":\"invalid openid\"}"
                return Content("用户已授权，授权Token：" + result);
            }
        }

        #endregion

        #region 授权信息

        public ActionResult GetAuthorizerInfoResult(string authorizerId)
        {
            var getAuthorizerInfoResult = AuthorizerContainer.GetAuthorizerInfoResult(component_AppId, authorizerId);
            return Json(getAuthorizerInfoResult);
        }

        public ActionResult RefreshAuthorizerAccessToken(string authorizerId)
        {
            var componentAccessToken = ComponentContainer.GetComponentAccessToken(component_AppId);
            var authorizationInfo = AuthorizerContainer.GetAuthorizationInfo(component_AppId, authorizerId);
            if (authorizationInfo == null)
            {
                return Content("授权信息读取失败！");
            }

            var refreshToken = authorizationInfo.authorizer_refresh_token;
            var result = AuthorizerContainer.RefreshAuthorizerToken(componentAccessToken, component_AppId, authorizerId,
                refreshToken);
            return Json(result);
        }

        #endregion
    }
}

Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Views/OpenOAuth/Index.cshtml
@* DPBMARK_FILE Open *@
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>开放平台OAuth授权测试</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <h2>开放平台OAuth2.0授权测试</h2>
    <p>注意：此页面仅供测试，测试号随时可能过期。请将此DEMO部署到您自己的服务器上，并使用自己的appid、Component_Appid及Component_AccessToken等参数。</p>
    <p><a href="@ViewData["UrlUserInfo"]">点击这里测试snsapi_userinfo</a></p>
    <p>
        将要链接到的地址：<br />
        <textarea rows="10" cols="40">@ViewData["UrlUserInfo"]</textarea>
    </p>
    <p><a href="@ViewData["UrlBase"]">点击这里测试snsapi_base</a></p>
    <p>
        将要链接到的地址：<br />
        <textarea rows="10" cols="40">@ViewData["UrlBase"]</textarea>
    </p>
</body>
</html>

Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Views/OpenOAuth/JumpToMpOAuth.cshtml
@* DPBMARK_FILE Open *@
@{
    ViewBag.Title = "跳转到公众号授权页";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section HeaderContent{
    <style>
        h1 {
            text-align: center;
            font-size: 30px;
            padding: 30px;
        }

        .enter {
            font-size: 200%;
            font-weight: bold;
            text-align: center;
        }

        .wrapper p {
            margin-bottom: 20px;
            line-height: 130%;
        }

        .wrapper.center {
            text-align: center;
        }

        strong {
            font-size: 150%;
        }
    </style>
}
<div class="wrapper">
    <h1>跳转到公众号授权页</h1>

    <div>
        <p class="center">
            <strong>说明</strong><br />
            1、授权页必须由合法（已经审核通过）的域名进入。<br />
            2、直接打开，或者在外部网站链接过来都可能被拒绝。<br />
            3、因此测试的时候必须有这样一个Referer页面存在。<br />
        </p>
    </div>
    <div>
        <p class="enter">
            @Html.ActionLink("点击这里进入公众号授权页", "OAuth", "Open", null, new { @class = "application" })
        </p>
        <p>&nbsp;</p>
    </div>
</div>

Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Views/OpenOAuth/OpenOAuthCallback.cshtml
@using Senparc.Weixin.Open.ComponentAPIs
@* DPBMARK_FILE Open *@
@{
    Layout = null;

    var authInfo = ViewData["QueryAuthorizationInfo"] as AuthorizationInfo;
    var autherInfo = ViewData["GetAuthorizerInfoResult"] as AuthorizerInfo;

    if (autherInfo == null)
    {
        throw new Exception("SS");
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>成功授权</title>
</head>
<body>
    <h1>账号已成功授权</h1>
    <section>
        <h2>授权信息</h2>
        <p>authorizer_access_token：@authInfo.authorizer_access_token</p>
        <p>authorizer_appid：@authInfo.authorizer_appid</p>
        <p>authorizer_refresh_token：@authInfo.authorizer_refresh_token</p>
        <p>expires_in：@authInfo.expires_in</p>
        <p>
            func_info：<br />
            @if (authInfo.func_info != null)
            {
                foreach (var item in authInfo.func_info)
                {
                    <span>&nbsp; &nbsp; @(item.funcscope_category != null ? item.funcscope_category.id.ToString() : "空（异常情况）")</span><br />
                }
            }
            else
            {
                <span>空（异常情况）</span>
            }
        </p>
    </section>
    <section>
        <h2>授权公众号信息</h2>
        <p>
            <img src="@autherInfo.head_img" style="width: 100px;" />
            <img src="@autherInfo.qrcode_url" style="width: 100px;" />
        </p>
        <p>alias：@autherInfo.alias</p>
        <p>nick_name：@autherInfo.nick_name</p>
        <p>user_name：@autherInfo.user_name</p>
        <p>service_type_info：@autherInfo.service_type_info.id</p>
        <p>verify_type_info：@autherInfo.verify_type_info.id</p>
        <h2>授权信息</h2>
        <p>appid：@authInfo.authorizer_appid</p>
    </section>
    <section>
        <h2>查看授权缓存信息</h2>
        <p>
            @Html.ActionLink("点击查看", "GetAuthorizerInfoResult", "OpenOAuth", new { authorizerId = authInfo.authorizer_appid }, new { target = "_blank" })<br />
        </p>
        <p>
            @Html.ActionLink("刷新AuthorizerAccessToken", "RefreshAuthorizerAccessToken", "OpenOAuth", new { authorizerId = authInfo.authorizer_appid }, new { target = "_blank" })<br />
        </p>
    </section>
    <section>
        <h2>用户授权测试</h2>
        <p>

            @Html.ActionLink("点击开始用户授权测试", "Index", "OpenOAuth", new { appId = authInfo.authorizer_appid }, null)<br />
            注意：测试之前请先确认您的公众号有OAuth的权限，否则可能会返回错误：Scope 参数错误或没有 Scope 权限。
        </p>
    </section>

</body>
</html>

Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Views/OpenOAuth/UserInfoCallback.cshtml
@model Senparc.Weixin.Open.OAuthAPIs.OAuthUserInfo
@* DPBMARK_FILE Open *@
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>开放平台OAuth授权测试</title>
</head>
<body>
    <h2>开放平台OAuth2.0授权测试授权成功！</h2>
    @if (ViewData.ContainsKey("ByBase"))
    {
        <p><strong>您看到的这个页面来自于snsapi_base授权，因为您已关注本微信，所以才能查询到详细用户信息，否则只能进行常规的授权。</strong></p>
    }
    else
    {
        <p><strong>您看到的这个页面来自于snsapi_userinfo授权，可以直接获取到用户详细信息。</strong></p>
    }
    <p>下面是通过授权得到的您的部分个人信息：</p>
    <p>nickname:@Model.nickname</p>
    <p>country:@Model.country</p>
    <p>province:@Model.province</p>
    <p>city:@Model.city</p>
    <p>sex:@Model.sex</p>
    <p>
        头像：<br />
        <img src="@Model.headimgurl" />（直接调用可能看不到，需要抓取）
    </p>
</body>
</html>